/*! Versions generated by sVersion on 2026-06-17 23:19 */
/*! \note this generated file should NOT be added to Git repository, include in .gitignore to avoid */
#ifndef AUTOVERSION_H
#define AUTOVERSION_H

#include "C_defs.h"

#define VERSION_MAJOR            ( 4u )
#define VERSION_MINOR            ( 0u )
#define VERSION_PATCH            ( 7u )
#define VERSION_RELEASE_TYPE     "323d349"
#define BUILD_ID                 ( 323d349 )
/* local build from commit 323d349 */

#define BUILD_DATE                      ( 17u )
#define BUILD_MONTH                     ( 6u )
#define BUILD_YEAR                      ( 2026u )

#endif